import { defineStore } from "pinia";

export const useTypeDirStore = defineStore("typeDir", {
    state: () => ({
        entries: {
            en: "entries",
            fr: "entrées",
            pt: "entradas",
            de: "Einträge",
            zh: "条目",
            ja: "項目",
            es: "entradas",
            ko: "항목",
            ar: "إدخالات",
        },
        typeDirectory: {
            en: "Type directory",
            fr: "Répertoire des types",
            pt: "Diretório de tipos",
            de: "Typverzeichnis",
            zh: "类型目录",
            ja: "型ディレクトリ",
            es: "Directorio de tipos",
            ko: "타입 디렉터리",
            ar: "دليل الأنواع",
        },
        fullTypesDirectory: {
            en: "full types directory",
            fr: "répertoire complet des types",
            pt: "diretório completo de tipos",
            de: "Vollständiges Typverzeichnis",
            zh: "完整类型目录",
            ja: "型ディレクトリ全体",
            es: "directorio completo de tipos",
            ko: "전체 타입 디렉터리",
            ar: "دليل الأنواع الكامل",
        },
        goBack: {
            en: "Go back",
            fr: "Retour",
            pt: "Voltar",
            de: "Zurück",
            zh: "返回",
            ja: "戻る",
            es: "Volver",
            ko: "뒤로",
            ar: "رجوع",
        },
        goForward: {
            en: "Go forward",
            fr: "Avancer",
            pt: "Avançar",
            de: "Vorwärts",
            zh: "前进",
            ja: "進む",
            es: "Avanzar",
            ko: "앞으로",
            ar: "تقدم",
        },
        openFile: {
            en: "Import .d.ts",
            fr: "Importer .d.ts",
            pt: "Importar .d.ts",
            de: ".d.ts importieren",
            zh: "导入 .d.ts",
            ja: ".d.ts をインポート",
            es: "Importar .d.ts",
            ko: ".d.ts 가져오기",
            ar: "استيراد .d.ts",
        },
        declarations: {
            en: "Declarations",
            fr: "Déclarations",
            pt: "Declarações",
            de: "Deklarationen",
            zh: "声明",
            ja: "宣言",
            es: "Declaraciones",
            ko: "선언",
            ar: "التصريحات",
        },
        searchDeclarations: {
            en: "SEARCH DECLARATIONS",
            fr: "RECHERCHER DES DÉCLARATIONS",
            pt: "PESQUISAR DECLARAÇÕES",
            de: "DEKLARATIONEN SUCHEN",
            zh: "搜索声明",
            ja: "宣言を検索",
            es: "BUSCAR DECLARACIONES",
            ko: "선언 검색",
            ar: "البحث في التصريحات",
        },
        searchPlaceholder: {
            en: "Type, interface, namespace…",
            fr: "Type, interface, espace de noms…",
            pt: "Tipo, interface, namespace…",
            de: "Typ, Interface, Namensraum…",
            zh: "类型、接口、命名空间…",
            ja: "型、インターフェース、名前空間…",
            es: "Tipo, interfaz, espacio de nombres…",
            ko: "타입, 인터페이스, 네임스페이스…",
            ar: "نوع، واجهة، مساحة أسماء…",
        },
        declarationTypes: {
            en: "Declaration types",
            fr: "Types de déclarations",
            pt: "Tipos de declaração",
            de: "Deklarationstypen",
            zh: "声明类型",
            ja: "宣言の種類",
            es: "Tipos de declaración",
            ko: "선언 유형",
            ar: "أنواع التصريحات",
        },
        noMatchingDeclarations: {
            en: "No matching declarations.",
            fr: "Aucune déclaration correspondante.",
            pt: "Nenhuma declaração correspondente.",
            de: "Keine passenden Deklarationen.",
            zh: "没有匹配的声明。",
            ja: "一致する宣言がありません。",
            es: "No hay declaraciones coincidentes.",
            ko: "일치하는 선언이 없습니다.",
            ar: "لا توجد تصريحات مطابقة.",
        },
        all: {
            en: "All",
            fr: "Tout",
            pt: "Todos",
            de: "Alle",
            zh: "全部",
            ja: "すべて",
            es: "Todos",
            ko: "전체",
            ar: "الكل",
        },
        interfaces: {
            en: "Interfaces",
            fr: "Interfaces",
            pt: "Interfaces",
            de: "Interfaces",
            zh: "接口",
            ja: "インターフェース",
            es: "Interfaces",
            ko: "인터페이스",
            ar: "واجهات",
        },
        typeAliases: {
            en: "Type aliases",
            fr: "Alias de types",
            pt: "Aliases de tipos",
            de: "Typaliase",
            zh: "类型别名",
            ja: "型エイリアス",
            es: "Alias de tipos",
            ko: "타입 별칭",
            ar: "أسماء الأنواع المستعارة",
        },
        classes: {
            en: "Classes",
            fr: "Classes",
            pt: "Classes",
            de: "Klassen",
            zh: "类",
            ja: "クラス",
            es: "Clases",
            ko: "클래스",
            ar: "فئات",
        },
        enums: {
            en: "Enums",
            fr: "Énumérations",
            pt: "Enumerações",
            de: "Aufzählungen",
            zh: "枚举",
            ja: "列挙型",
            es: "Enumeraciones",
            ko: "열거형",
            ar: "تعدادات",
        },
        functions: {
            en: "Functions",
            fr: "Fonctions",
            pt: "Funções",
            de: "Funktionen",
            zh: "函数",
            ja: "関数",
            es: "Funciones",
            ko: "함수",
            ar: "دوال",
        },
        namespaces: {
            en: "Namespaces / Modules",
            fr: "Espaces de noms / Modules",
            pt: "Namespaces / Módulos",
            de: "Namensräume / Module",
            zh: "命名空间 / 模块",
            ja: "名前空間 / モジュール",
            es: "Espacios de nombres / Módulos",
            ko: "네임스페이스 / 모듈",
            ar: "مساحات الأسماء / الوحدات",
        },
        variables: {
            en: "Variables",
            fr: "Variables",
            pt: "Variáveis",
            de: "Variablen",
            zh: "变量",
            ja: "変数",
            es: "Variables",
            ko: "변수",
            ar: "متغيرات",
        },
        types: {
            en: "Types",
            fr: "Types",
            pt: "Tipos",
            de: "Typen",
            zh: "类型",
            ja: "型",
            es: "Tipos",
            ko: "타입",
            ar: "الأنواع",
        },
        exported: {
            en: "exported",
            fr: "exporté",
            pt: "exportado",
            de: "exportiert",
            zh: "已导出",
            ja: "エクスポート済み",
            es: "exportado",
            ko: "내보냄",
            ar: "مُصدَّر",
        },
        declaration: {
            en: "Declaration",
            fr: "Déclaration",
            pt: "Declaração",
            de: "Deklaration",
            zh: "声明",
            ja: "宣言",
            es: "Declaración",
            ko: "선언",
            ar: "تصريح",
        },
        copied: {
            en: "Copied",
            fr: "Copié",
            pt: "Copiado",
            de: "Kopiert",
            zh: "已复制",
            ja: "コピー済み",
            es: "Copiado",
            ko: "복사됨",
            ar: "تم النسخ",
        },
        copyCode: {
            en: "Copy code",
            fr: "Copier le code",
            pt: "Copiar código",
            de: "Code kopieren",
            zh: "复制代码",
            ja: "コードをコピー",
            es: "Copiar código",
            ko: "코드 복사",
            ar: "نسخ الرمز",
        },
        navigationTip: {
            en: "Select a highlighted type to open its declaration. Use ← and → to navigate history.",
            fr: "Sélectionnez un type surligné pour ouvrir sa déclaration. Utilisez ← et → pour parcourir l’historique.",
            pt: "Selecione um tipo destacado para abrir sua declaração. Use ← e → para navegar no histórico.",
            de: "Wählen Sie einen markierten Typ, um seine Deklaration zu öffnen. Mit ← und → navigieren Sie im Verlauf.",
            zh: "选择高亮类型以打开其声明。使用 ← 和 → 浏览历史记录。",
            ja: "強調表示された型を選択すると宣言を開けます。← と → で履歴を移動できます。",
            es: "Seleccione un tipo resaltado para abrir su declaración. Use ← y → para navegar por el historial.",
            ko: "강조된 타입을 선택해 선언을 엽니다. ← 및 →로 기록을 탐색하세요.",
            ar: "اختر نوعًا مميزًا لفتح تصريحه. استخدم ← و → للتنقل في السجل.",
        },
        referencedDeclarations: {
            en: "Referenced declarations",
            fr: "Déclarations référencées",
            pt: "Declarações referenciadas",
            de: "Referenzierte Deklarationen",
            zh: "引用的声明",
            ja: "参照される宣言",
            es: "Declaraciones referenciadas",
            ko: "참조된 선언",
            ar: "التصريحات المشار إليها",
        },
        line: {
            en: "Line",
            fr: "Ligne",
            pt: "Linha",
            de: "Zeile",
            zh: "行",
            ja: "行",
            es: "Línea",
            ko: "줄",
            ar: "السطر",
        },
        emptyPrompt: {
            en: "Select a declaration to inspect it, or open a .d.ts file.",
            fr: "Sélectionnez une déclaration à examiner ou ouvrez un fichier .d.ts.",
            pt: "Selecione uma declaração para inspecionar ou abra um arquivo .d.ts.",
            de: "Wählen Sie eine Deklaration aus oder öffnen Sie eine .d.ts-Datei.",
            zh: "选择一个声明进行查看，或打开 .d.ts 文件。",
            ja: "宣言を選択して確認するか、.d.ts ファイルを開いてください。",
            es: "Seleccione una declaración para inspeccionarla o abra un archivo .d.ts.",
            ko: "살펴볼 선언을 선택하거나 .d.ts 파일을 여세요.",
            ar: "اختر تصريحًا لفحصه أو افتح ملف .d.ts.",
        },
        openReference: {
            en: "Open",
            fr: "Ouvrir",
            pt: "Abrir",
            de: "Öffnen",
            zh: "打开",
            ja: "開く",
            es: "Abrir",
            ko: "열기",
            ar: "فتح",
        },
        parseError: {
            en: "Unable to parse declaration file.",
            fr: "Impossible d’analyser le fichier de déclarations.",
            pt: "Não foi possível analisar o arquivo de declarações.",
            de: "Deklarationsdatei konnte nicht analysiert werden.",
            zh: "无法解析声明文件。",
            ja: "宣言ファイルを解析できません。",
            es: "No se pudo analizar el archivo de declaraciones.",
            ko: "선언 파일을 파싱할 수 없습니다.",
            ar: "تعذّر تحليل ملف التصريحات.",
        },
        readError: {
            en: "Unable to read file.",
            fr: "Impossible de lire le fichier.",
            pt: "Não foi possível ler o arquivo.",
            de: "Datei konnte nicht gelesen werden.",
            zh: "无法读取文件。",
            ja: "ファイルを読み込めません。",
            es: "No se pudo leer el archivo.",
            ko: "파일을 읽을 수 없습니다.",
            ar: "تعذّرت قراءة الملف.",
        },
        resetDirectory: {
            en: "Reset directory",
            fr: "Réinitialiser le répertoire",
            pt: "Redefinir diretório",
            de: "Verzeichnis zurücksetzen",
            zh: "重置目录",
            ja: "ディレクトリをリセット",
            es: "Restablecer directorio",
            ko: "디렉터리 초기화",
            ar: "إعادة تعيين الدليل",
        },
    }),
});
