export const defaultDataHill = {
    dataset: [
        {
            label: "Task A",
            position: 1,
            color: "#1f77b4",
            muted: false,
            disabled: false,
        },
        {
            label: "Task B",
            position: 0.5,
            color: "#aec7e8",
            muted: false,
            disabled: false,
        },
        {
            label: "Task C",
            position: 0.5,
            color: "#ff7f0e",
            muted: false,
            disabled: false,
        },
        {
            label: "Task D",
            position: 0,
            color: "#ffbb78",
            muted: false,
            disabled: false,
        },
    ],
    model: [
        {
            key: "loading",
            def: false,
            type: "checkbox",
            label: "loading",
            category: "general",
        },
        {
            key: "readonly",
            def: false,
            type: "checkbox",
            label: "readonly",
            category: "general",
        },
        {
            key: "editing",
            def: false,
            type: "checkbox",
            label: "editing",
            category: "general",
        },
        {
            key: "userOptions.show",
            def: true,
            type: "checkbox",
            label: "show",
            category: "userOptions",
        },
        {
            key: "userOptions.showOnChartHover",
            def: false,
            type: "checkbox",
            label: ["user options", "is", "show", "on", "hover"],
            category: "userOptions",
        },
        {
            key: "userOptions.keepStateOnChartLeave",
            def: true,
            type: "checkbox",
            label: ["user options", "is", "keep state on leave"],
            category: "userOptions",
        },
        {
            key: "userOptions.position",
            def: "right",
            type: "select",
            options: ["right", "left"],
            label: ["position"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttons.pdf",
            def: true,
            type: "checkbox",
            label: ["button", "pdf", "is", "show"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttons.img",
            def: true,
            type: "checkbox",
            label: ["button", "img", "is", "show"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttons.svg",
            def: true,
            type: "checkbox",
            label: ["button", "svg", "is", "show"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttons.csv",
            def: true,
            type: "checkbox",
            label: ["button", "csv", "is", "show"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttons.fullscreen",
            def: true,
            type: "checkbox",
            label: ["button", "fullscreen", "is", "show"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttons.annotator",
            def: true,
            type: "checkbox",
            label: ["button", "annotator", "is", "show"],
            category: "userOptions",
        },

        {
            key: "userOptions.buttonTitles.open",
            def: "Open options",
            type: "text",
            label: ["button", "open", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttonTitles.close",
            def: "Close options",
            type: "text",
            label: ["button", "close", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttonTitles.pdf",
            def: "Download PDF",
            type: "text",
            label: ["button", "pdf", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttonTitles.csv",
            def: "Download CSV",
            type: "text",
            label: ["button", "csv", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttonTitles.img",
            def: "Download PNG",
            type: "text",
            label: ["button", "img", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttonTitles.svg",
            def: "Download SVG",
            type: "text",
            label: ["button", "svg", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttonTitles.fullscreen",
            def: "Toggle fullscreen",
            type: "text",
            label: ["button", "fullscreen", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "userOptions.buttonTitles.annotator",
            def: "Toggle annotator",
            type: "text",
            label: ["button", "annotator", "title", "is", "textContent"],
            category: "userOptions",
        },
        {
            key: "style.chart.toolbar.show",
            def: true,
            type: "checkbox",
            label: "show",
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.status.lastUpdated",
            def: "Last updated [date]",
            type: "text",
            label: ["status", "is", "last updated"],
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.status.editInstruction",
            def: "Drag each dot to adjust its position",
            type: "text",
            label: ["status", "is", "instructions"],
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.status.color",
            def: "#1A1A1A",
            type: "color",
            label: "textColor",
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.status.fontSize",
            def: 14,
            type: "number",
            min: 8,
            max: 24,
            label: ["status", "is", "fontSize"],
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.bold",
            def: false,
            type: "checkbox",
            label: ["status", "is", "bold"],
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.lineHeight",
            def: 1.3,
            type: "number",
            min: 0,
            max: 12,
            step: 0.1,
            label: ["status", "is", "lineHeight"],
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.buttons.translations.edit",
            def: "Edit",
            type: "text",
            label: ["button", "edit", "is", "name"],
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.buttons.translations.cancel",
            def: "Cancel",
            type: "text",
            label: ["button", "cancel", "is", "name"],
            category: "editMenu",
        },
        {
            key: "style.chart.toolbar.buttons.translations.save",
            def: "Save",
            type: "text",
            label: ["button", "save", "is", "name"],
            category: "editMenu",
        },

        {
            key: "style.chart.layout.hill.geometry.horizontalPaddingRatio",
            def: 0.05,
            type: "number",
            min: 0,
            max: 0.3,
            step: 0.01,
            label: ["horizontal", "padding", "is", "ratio"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.geometry.topPaddingRatio",
            def: 0.15,
            type: "number",
            min: 0,
            max: 0.5,
            step: 0.01,
            label: ["top", "padding", "is", "ratio"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.geometry.bottomPaddingRatio",
            def: 0.15,
            type: "number",
            min: 0,
            max: 0.5,
            step: 0.01,
            label: ["bottom", "padding", "is", "ratio"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.geometry.curvature",
            def: 0.7,
            type: "number",
            min: 0.1,
            max: 1,
            step: 0.01,
            label: ["curve", "is", "ratio"],
            category: "layout",
        },

        {
            key: "style.chart.layout.hill.curve.stroke",
            def: "#A1A1A1",
            type: "color",
            label: ["curve", "is", "color"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.curve.strokeWidth",
            def: 1.5,
            type: "number",
            min: 0,
            max: 12,
            step: 0.5,
            label: ["curve", "is", "thickness"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.curve.strokeDasharray",
            def: "0",
            type: "text",
            label: ["curve", "is", "strokeDasharray"],
            category: "layout",
        },

        {
            key: "style.chart.layout.hill.baseline.show",
            def: true,
            type: "checkbox",
            label: ["baseline", "is", "show"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.baseline.stroke",
            def: "#CCCCCC",
            type: "color",
            label: ["baseline", "is", "color"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.baseline.strokeWidth",
            def: 1,
            type: "number",
            min: 0,
            max: 6,
            step: 0.5,
            label: ["baseline", "is", "thickness"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.baseline.strokeDasharray",
            def: "0",
            type: "text",
            label: ["baseline", "is", "strokeDasharray"],
            category: "layout",
        },

        {
            key: "style.chart.layout.hill.midline.show",
            def: true,
            type: "checkbox",
            label: ["midline", "is", "show"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.midline.stroke",
            def: "#CCCCCC",
            type: "color",
            label: ["midline", "is", "color"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.midline.strokeWidth",
            def: 1,
            type: "number",
            min: 0,
            max: 6,
            step: 0.5,
            label: ["midline", "is", "thickness"],
            category: "layout",
        },
        {
            key: "style.chart.layout.hill.midline.strokeDasharray",
            def: "2.5 3.5",
            type: "text",
            label: ["midline", "is", "strokeDasharray"],
            category: "layout",
        },

        {
            key: "style.chart.layout.plots.radius",
            def: 10,
            type: "number",
            min: 4,
            max: 20,
            step: 0.5,
            label: ["circles", "is", "radius"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.hitRadius",
            def: 10,
            type: "number",
            min: 4,
            max: 30,
            step: 0.5,
            label: ["circles", "is", "hit", "radius"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.stroke",
            def: "#FFFFFF",
            type: "color",
            label: ["circles", "border", "is", "color"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.strokeWidth",
            def: 2,
            type: "number",
            min: 0,
            max: 6,
            step: 0.5,
            label: ["circles", "border", "is", "thickness"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.mutedOpacity",
            def: 0.4,
            type: "number",
            min: 0.1,
            max: 0.8,
            step: 0.05,
            label: ["circles", "muted", "is", "opacity"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.disabledOpacity",
            def: 0.4,
            type: "number",
            min: 0.1,
            max: 0.8,
            step: 0.05,
            label: ["circles", "disabled", "is", "opacity"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.shadow.show",
            def: true,
            type: "checkbox",
            label: ["circles", "shadow", "is", "show"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.shadow.color",
            def: "#1A1A1A",
            type: "color",
            label: ["circles", "shadow", "is", "color"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.shadow.offsetX",
            def: 0,
            min: -12,
            max: 12,
            step: 0.5,
            type: "number",
            label: ["circles", "shadow", "is", "offsetX"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.shadow.offsetY",
            def: 0.5,
            min: -12,
            max: 12,
            step: 0.5,
            type: "number",
            label: ["circles", "shadow", "is", "offsetY"],
            category: "datapoints",
        },
        {
            key: "style.chart.layout.plots.shadow.blur",
            def: 0.4,
            min: 0,
            max: 24,
            step: 0.5,
            type: "number",
            label: ["circles", "shadow", "is", "blur"],
            category: "datapoints",
        },

        {
            key: "style.chart.layout.plots.stacking.show",
            def: true,
            type: "checkbox",
            label: ["show"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overlapThresholdRatio",
            type: "number",
            def: 0.8,
            min: 0.2,
            max: 1,
            step: 0.01,
            label: ["overlap", "threshold", "is", "ratio"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.gap",
            type: "number",
            def: 5,
            min: -10,
            max: 50,
            label: ["gap"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.show",
            type: "checkbox",
            def: true,
            label: ["overflow", "is", "show"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.transitionDuration",
            type: "number",
            min: 0,
            max: 1000,
            step: 50,
            label: ["overflow", "transition", "is", "duration"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.radius",
            def: 10,
            type: "number",
            min: 4,
            max: 24,
            label: ["overflow", "marker", "is", "size"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.fill",
            type: "color",
            def: "#CCCCCC",
            label: ["overflow", "marker", "is", "color"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.stroke",
            def: "#FFFFFF",
            type: "color",
            label: ["overflow", "marker", "border", "is", "color"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.strokeWidth",
            def: 1,
            type: "number",
            min: 0,
            max: 6,
            step: 0.5,
            label: ["overflow", "marker", "border", "is", "thickness"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.labelColor",
            def: "#1A1A1A",
            type: "color",
            label: ["overflow", "marker", "label", "is", "textColor"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.labelOffsetY",
            type: "number",
            def: 0,
            min: -64,
            max: 64,
            label: ["overflow", "marker", "label", "is", "offsetY"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.fontSize",
            type: "number",
            def: 14,
            min: 8,
            max: 24,
            label: ["overflow", "marker", "label", "is", "fontSize"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.marker.bold",
            type: "checkbox",
            def: false,
            label: ["overflow", "marker", "label", "is", "bold"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.menu.width",
            type: "number",
            def: 220,
            min: 200,
            max: 400,
            step: 10,
            label: ["overflow", "menu", "is", "width"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.menu.maxHeight",
            type: "number",
            def: 220,
            min: 200,
            max: 1000,
            step: 10,
            label: ["overflow", "menu", "is", "maxHeight"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.menu.backgroundColor",
            type: "color",
            def: "#FFFFFF",
            label: ["overflow", "menu", "is", "backgroundColor"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.menu.color",
            type: "color",
            def: "#1A1A1A",
            label: ["overflow", "menu", "is", "textColor"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.menu.borderColor",
            type: "color",
            def: "transparent",
            label: ["overflow", "menu", "border", "is", "color"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.menu.borderRadius",
            type: "number",
            def: 3,
            min: 0,
            max: 12,
            label: ["overflow", "menu", "border", "is", "radius"],
            category: "stacking",
        },
        {
            key: "style.chart.layout.plots.stacking.overflow.menu.title",
            type: "text",
            def: "",
            label: ["overflow", "menu", "is", "title"],
            category: "stacking",
        },

        // { key: 'style.chart.layout.plots.dragMarker.show', type: 'checkbox', def: true, label: ['show'], category: 'selector'},
        // { key: 'style.chart.layout.plots.dragMarker.strokeWidth', type: 'number', def: 1.5, min: 0, max: 6, step: 0.5, label: ['thickness'], category: 'selector'},
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.show",
            def: true,
            type: "checkbox",
            label: ["show"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.useSerieColor",
            type: "checkbox",
            def: true,
            label: "use series color",
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.color",
            type: "color",
            def: "#E1E5E8",
            label: ["color", "is", "default"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.strokeWidth",
            type: "number",
            def: 1,
            min: 0,
            max: 6,
            step: 0.5,
            label: ["thickness"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.strokeDasharray",
            type: "text",
            def: "2 4",
            label: ["strokeDasharray"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.circle.show",
            type: "checkbox",
            def: true,
            label: ["circle", "is", "show"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.circle.radius",
            type: "number",
            def: 3,
            min: 0,
            max: 10,
            step: 0.5,
            label: ["circle", "is", "radius"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.circle.stroke",
            type: "color",
            def: "#FFFFFF",
            label: ["circle", "border", "is", "color"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.circle.strokeWidth",
            type: "number",
            def: 1,
            min: 0,
            max: 6,
            label: ["circle", "border", "is", "thickness"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.value.show",
            type: "chekbox",
            def: true,
            label: ["value", "is", "show"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.value.offsetY",
            type: "number",
            def: 0,
            min: -64,
            max: 64,
            label: ["value", "is", "offsetY"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.value.fontSize",
            type: "number",
            def: 12,
            min: 8,
            max: 42,
            label: ["value", "is", "fontSize"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.value.useSerieColor",
            type: "checkbox",
            def: false,
            label: ["value", "is", "use series color"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.value.color",
            type: "color",
            def: "#1A1A1A",
            label: ["value", "is", "default", "color"],
            category: "selector",
        },
        {
            key: "style.chart.layout.plots.dragMarker.positionIndicator.value.rounding",
            type: "number",
            def: 0,
            min: 0,
            max: 3,
            label: ["value", "is", "rounding"],
            category: "selector",
        },

        {
            key: "style.chart.layout.labels.item.show",
            type: "checkbox",
            def: true,
            label: ["datapoint", "is", "show"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.ellipsisThresholdChars",
            type: "number",
            def: 24,
            min: 12,
            max: 50,
            label: ["datapoint", "ellipsis", "is", "threshold"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.useSerieColor",
            type: "checkbox",
            def: false,
            label: ["datapoint", "is", "use serie color"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.color",
            type: "color",
            def: "#1A1A1A",
            label: ["datapoint", "is", "default", "color"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.fontSize",
            type: "number",
            def: 14,
            min: 8,
            max: 24,
            label: ["datapoint", "is", "fontSize"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.bold",
            type: "checkbox",
            def: false,
            label: ["datapoint", "is", "bold"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.offsetX",
            type: "number",
            def: 0,
            min: -64,
            max: 64,
            label: ["datapoint", "is", "offsetX"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.offsetY",
            type: "number",
            def: 0,
            min: -64,
            max: 64,
            label: ["datapoint", "is", "offsetY"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.autoSideThreshold",
            type: "number",
            def: 0.75,
            min: 0.5,
            max: 1,
            step: 0.01,
            label: ["datapoint", "is", "auto side threshold"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.stroke",
            type: "color",
            def: "#FFFFFF",
            label: ["datapoint", "border", "is", "color"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.item.strokeWdith",
            type: "number",
            def: 5,
            min: 0,
            max: 10,
            step: 0.5,
            label: ["datapoint", "border", "is", "thickness"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.phases.show",
            type: "checkbox",
            def: true,
            label: ["phases", "is", "show"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.phases.color",
            type: "color",
            def: "#A1A1A1",
            label: ["phases", "is", "textColor"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.phases.fontSize",
            type: "number",
            def: 14,
            min: 8,
            max: 42,
            label: ["phases", "is", "fontSize"],
        },
        {
            key: "style.chart.layout.labels.phases.bold",
            type: "checkbox",
            def: true,
            label: ["phases", "is", "bold"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.phases.letterSpacing",
            type: "text",
            def: "0.1em",
            label: ["phases", "is", "letterSpacing"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.phases.offsetY",
            type: "number",
            def: 0,
            min: -64,
            max: 64,
            label: ["phases", "is", "offsetY"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.phases.left.text",
            type: "text",
            def: "FIGURING THINGS OUT",
            label: ["phases", "left", "is", "textContent"],
            category: "labels",
        },
        {
            key: "style.chart.layout.labels.phases.right.text",
            type: "text",
            def: "MAKING IT HAPPEN",
            label: ["phases", "right", "is", "textContent"],
            category: "labels",
        },

        {
            key: "style.chart.layout.stackbar.show",
            type: "checkbox",
            def: true,
            label: "show",
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.paddingTop",
            type: "number",
            def: 0,
            min: 0,
            max: 100,
            label: ["padding", "is", "top"],
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.paddingBottom",
            type: "number",
            def: 12,
            min: 0,
            max: 100,
            label: ["padding", "is", "bottom"],
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.height",
            type: "number",
            def: 14,
            min: 6,
            max: 24,
            label: "height",
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.stroke",
            type: "color",
            def: "#FFFFFF",
            label: ["border", "is", "color"],
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.strokeWidth",
            type: "number",
            def: 1.5,
            min: 0,
            max: 6,
            step: 0.1,
            label: ["border", "is", "thickness"],
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.gutterColor",
            type: "color",
            def: "#E1E5E8",
            label: ["gutter", "is", "color"],
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.label.show",
            type: "checkbox",
            def: true,
            label: ["label", "is", "show"],
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.label.color",
            type: "color",
            def: "#1A1A1A",
            label: ["label", "is", "textColor"],
            category: "stackbar",
        },
        {
            key: "style.chart.layout.stackbar.label.fontSize",
            type: "number",
            def: 12,
            min: 8,
            max: 42,
            label: ["label", "is", "fontSize"],
            category: "stackbar",
        },

        {
            key: "style.chart.title.text",
            def: "",
            type: "text",
            label: "textContent",
            category: "title",
        },
        {
            key: "style.chart.title.color",
            def: "#1A1A1A",
            type: "color",
            label: "textColor",
            category: "title",
        },
        {
            key: "style.chart.title.fontSize",
            def: 20,
            type: "number",
            min: 6,
            max: 48,
            label: "fontSize",
            category: "title",
        },
        {
            key: "style.chart.title.bold",
            def: true,
            type: "checkbox",
            label: "bold",
            category: "title",
        },
        {
            key: "style.chart.title.textAlign",
            def: "center",
            type: "select",
            options: ["left", "center", "right"],
            label: "textAlign",
            category: "title",
        },
        {
            key: "style.chart.title.paddingLeft",
            def: 0,
            type: "number",
            min: 0,
            max: 24,
            label: ["padding", "is", "left"],
            category: "title",
        },
        {
            key: "style.chart.title.paddingRight",
            def: 0,
            type: "number",
            min: 0,
            max: 24,
            label: ["padding", "is", "right"],
            category: "title",
        },

        {
            key: "style.chart.title.subtitle.text",
            def: "",
            type: "text",
            label: "textContent",
            category: "subtitle",
        },
        {
            key: "style.chart.title.subtitle.color",
            def: "#A1A1A1",
            type: "color",
            label: "textColor",
            category: "subtitle",
        },
        {
            key: "style.chart.title.subtitle.fontSize",
            def: 16,
            type: "number",
            min: 6,
            max: 42,
            label: "fontSize",
            category: "subtitle",
        },
        {
            key: "style.chart.title.subtitle.bold",
            def: false,
            type: "checkbox",
            label: "bold",
            category: "subtitle",
        },
    ],
};
