export function useChartSlots(component) {

    const VDUI_SLOTS = {
        ARROW: 'arrow',
        AVERAGE: 'average',
        BEFORE: 'before',
        CAPTION: 'caption',
        CELL: 'cell',
        CHART_BACKGROUND: 'chart-background',
        COMMENT_AFTER: 'comment-after',
        COMMENT_BEFORE: 'comment-before',
        CONTENT: 'content',
        CONTROLS: 'controls',
        DATALABEL: 'dataLabel',
        DATA_LABEL: 'data-label',
        LAPS: 'laps',
        LEGEND: 'legend',
        MEDIAN: 'median',
        OPTION_ANIMATION: 'optionAnimation',
        OPTION_ANNOTATOR: 'optionAnnotator',
        OPTION_CSV: 'optionCsv',
        OPTION_FULLSCREEN: 'optionFullscreen',
        OPTION_IMG: 'optionImg',
        OPTION_LABELS: 'optionLabels',
        OPTION_PDF: 'optionPdf',
        OPTION_SORT: 'optionSort',
        OPTION_STACK: 'optionStack',
        OPTION_TABLE: 'optionTable',
        OPTION_TOOLTIP: 'optionTooltip',
        PATTERN: 'pattern',
        PLOT_COMMENT: 'plot-comment',
        RECT: 'rect',
        RESET_ACTION: 'reset-action',
        ROW_TITLE: 'rowTitle',
        SOURCE: 'source',
        SUM: 'sum',
        SVG: 'svg',
        TD: 'td',
        TH: 'th',
        TIME: 'time',
        TIME_LABEL: 'time-label',
        TITLE: 'title',
        TOOLTIP_AFTER: 'tooltip-after',
        TOOLTIP_BEFORE: 'tooltip-before',
        VALUE: 'value',
        WATERMARK: 'watermark',
    };

    const slotsMap = {
        vue_ui_rings: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_donut: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.DATALABEL,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.PLOT_COMMENT,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_treemap: [
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.RECT,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_nested_donuts: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_sparkline: [
            VDUI_SLOTS.BEFORE,
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
        ],
        vue_ui_sparkbar: [
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.DATA_LABEL,
            VDUI_SLOTS.TITLE
        ],
        vue_ui_sparkstackbar: [
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
        ],
        vue_ui_sparkhistogram: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.SOURCE
        ],
        vue_ui_sparkgauge: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.SOURCE
        ],
        vue_ui_spark_trend: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.SOURCE
        ],
        vue_ui_gizmo: [],
        vue_ui_quick_chart: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_kpi: [
            VDUI_SLOTS.COMMENT_AFTER,
            VDUI_SLOTS.COMMENT_BEFORE,
            VDUI_SLOTS.TITLE,
            VDUI_SLOTS.VALUE,
        ],
        vue_ui_bullet: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_xy: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_STACK,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.PLOT_COMMENT,
            VDUI_SLOTS.RESET_ACTION,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TIME_LABEL,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_xy_canvas: [
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_STACK,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.RESET_ACTION,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_vertical_bar: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_SORT,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_horizontal_bar: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_SORT,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_parallel_coordinate_plot: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.PLOT_COMMENT,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_flow: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_candlestick: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.RESET_ACTION,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_age_pyramid: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_stackbar: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TIME_LABEL,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_donut_evolution: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.RESET_ACTION,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_chestnut: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_gauge: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_onion: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_wheel: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_tiremarks: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_thermometer: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_timer: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.CONTROLS,
            VDUI_SLOTS.LAPS,
            VDUI_SLOTS.TIME,
        ],
        vue_ui_word_cloud: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.RESET_ACTION,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_relation_circle: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_radar: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_mood_radar: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_quadrant: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_scatter: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_molecule: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_strip_plot: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_LABELS,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_dumbbell: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_3d_bar: [
            VDUI_SLOTS.CHART_BACKGROUND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_table_sparkline: [
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.SOURCE,
        ],
        vue_ui_waffle: [
            VDUI_SLOTS.CELL,
            VDUI_SLOTS.LEGEND,
            VDUI_SLOTS.OPTION_ANNOTATOR,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.OPTION_TABLE,
            VDUI_SLOTS.OPTION_TOOLTIP,
            VDUI_SLOTS.PATTERN,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.SVG,
            VDUI_SLOTS.TOOLTIP_AFTER,
            VDUI_SLOTS.TOOLTIP_BEFORE,
            VDUI_SLOTS.WATERMARK,
        ],
        vue_ui_table_heatmap: [
            VDUI_SLOTS.AVERAGE,
            VDUI_SLOTS.CAPTION,
            VDUI_SLOTS.CELL,
            VDUI_SLOTS.MEDIAN,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.ROW_TITLE,
            VDUI_SLOTS.SUM,
        ],
        vue_ui_table: [],
        vue_ui_carousel_table: [
            VDUI_SLOTS.CAPTION,
            VDUI_SLOTS.OPTION_ANIMATION,
            VDUI_SLOTS.OPTION_CSV,
            VDUI_SLOTS.OPTION_FULLSCREEN,
            VDUI_SLOTS.OPTION_IMG,
            VDUI_SLOTS.OPTION_PDF,
            VDUI_SLOTS.SOURCE,
            VDUI_SLOTS.TD,
            VDUI_SLOTS.TH,
        ],
        vue_ui_rating: [],
        vue_ui_smiley: [],
        vue_ui_accordion: [
            VDUI_SLOTS.ARROW,
            VDUI_SLOTS.CONTENT,
            VDUI_SLOTS.TITLE,
        ],
        vue_ui_skeleton: [],
        vue_ui_dashboard: [
            VDUI_SLOTS.CONTENT
        ],
        vue_ui_annotator: [],
        vue_ui_icon: [],
        vue_ui_digits: [],
        vue_ui_cursor: [],
        vue_ui_mini_loader: [],
    }

    return slotsMap[component];
}

export default {
    useSlotChecker
}