import { VueUiMiniLoader } from "vue-data-ui";

export function useImportMap(c) {
    const mapping = {
        VueDataUi: null,
        VueUiBullet: 'vue-ui-bullet',
        VueUi3dBar: 'vue-ui-3d-bar',
        VueUiAccordion: 'vue-ui-accordion',
        VueUiAgePyramid: 'vue-ui-age-pyramid',
        VueUiAnnotator: 'vue-ui-annotator',
        VueUiCandlestick: 'vue-ui-candlestick',
        VueUiCarouselTable: 'vue-ui-carousel-table',
        VueUiChestnut: 'vue-ui-chestnut',
        VueUiCursor: 'vue-ui-cursor',
        VueUiDashboard: 'vue-ui-dashboard',
        VueUiDigits: 'vue-ui-digits',
        VueUiDonut: 'vue-ui-donut',
        VueUiDonutEvolution: 'vue-ui-donut-evolution',
        VueUiDumbbell: 'vue-ui-dumbbell',
        VueUiFlow: 'vue-ui-flow',
        VueUiGalaxy: 'vue-ui-galaxy',
        VueUiGauge: 'vue-ui-gauge',
        VueUiHeatmap: 'vue-ui-heatmap',
        VueUiIcon: 'vue-ui-icon',
        VueUiKpi: 'vue-ui-kpi',
        VueUiMiniLoader: 'vue-ui-mini-loader',
        VueUiMolecule: 'vue-ui-molecule',
        VueUiMoodRadar: 'vue-ui-mood-radar',
        VueUiNestedDonuts: 'vue-ui-nested-donuts',
        VueUiOnion: 'vue-ui-onion',
        VueUiParallelCoordinatePlot: 'vue-ui-parallel-coordinate-plot',
        VueUiQuadrant: 'vue-ui-quadrant',
        VueUiQuickChart: 'vue-ui-quick-chart',
        VueUiRadar: 'vue-ui-radar',
        VueUiRating: 'vue-ui-rating',
        VueUiRelationCircle: 'vue-ui-relation-circle',
        VueUiRings: 'vue-ui-rings',
        VueUiScatter: 'vue-ui-scatter',
        VueUiScreenshot: 'vue-ui-screenshot',
        VueUiSkeleton: 'vue-ui-skeleton',
        VueUiSmiley: 'vue-ui-smiley',
        VueUiSparkHistogram: 'vue-ui-sparkhistogram',
        VueUiSparkStackbar: 'vue-ui-sparkstackbar',
        VueUiSparkTrend: 'vue-ui-spark-trend',
        VueUiSparkbar: 'vue-ui-sparkbar',
        VueUiSparkgauge: 'vue-ui-sparkgauge',
        VueUiSparkline: 'vue-ui-sparkline',
        VueUiStripPlot: 'vue-ui-strip-plot',
        VueUiTable: 'vue-ui-table',
        VueUiTableHeatmap: 'vue-ui-table-heatmap',
        VueUiTableSparkline: 'vue-ui-table-sparkline',
        VueUiThermometer: 'vue-ui-thermometer',
        VueUiTimer: 'vue-ui-timer',
        VueUiTiremarks: 'vue-ui-tiremarks',
        VueUiTreemap: 'vue-ui-treemap',
        VueUiHorizontalBar: 'vue-ui-horizontal-bar',
        VueUiWaffle: 'vue-ui-waffle',
        VueUiWheel: 'vue-ui-wheel',
        VueUiWordCloud: 'vue-ui-word-cloud',
        VueUiXy: 'vue-ui-xy',
        VueUiXyCanvas: 'vue-ui-xy-canvas',
        VueUiGizmo: 'vue-ui-gizmo',
        VueUiStackbar: 'vue-ui-stackbar',
        VueUiFunnel: 'vue-ui-funnel',
        VueUiHistoryPlot: 'vue-ui-history-plot',
        VueUiCirclePack: 'vue-ui-circle-pack',
        VueUiWorld: 'vue-ui-world',
        VueUiRidgeline: 'vue-ui-ridgeline',
        VueUiChord: 'vue-ui-chord',
        VueUiStackline: 'vue-ui-stackline'
    }
    return mapping[c] ? {
        classic: `import { ${c} } from "vue-data-ui";`,
        treeshaken: `import { ${c} } from "vue-data-ui/${mapping[c]}";`
    } : null;
}