export function useImportMap(c) {
    const mapping = {
        VueDataUi: null,
        VueUiBullet: "vue-ui-bullet",
        VueUi3dBar: "vue-ui-3d-bar",
        VueUiAccordion: "vue-ui-accordion",
        VueUiAgePyramid: "vue-ui-age-pyramid",
        VueUiAnnotator: "vue-ui-annotator",
        VueUiCandlestick: "vue-ui-candlestick",
        VueUiCarouselTable: "vue-ui-carousel-table",
        VueUiChestnut: "vue-ui-chestnut",
        VueUiCursor: "vue-ui-cursor",
        VueUiDashboard: "vue-ui-dashboard",
        VueUiDigits: "vue-ui-digits",
        VueUiDonut: "vue-ui-donut",
        VueUiDonutEvolution: "vue-ui-donut-evolution",
        VueUiDumbbell: "vue-ui-dumbbell",
        VueUiFlow: "vue-ui-flow",
        VueUiGalaxy: "vue-ui-galaxy",
        VueUiGauge: "vue-ui-gauge",
        VueUiHeatmap: "vue-ui-heatmap",
        VueUiIcon: "vue-ui-icon",
        VueUiKpi: "vue-ui-kpi",
        VueUiMiniLoader: "vue-ui-mini-loader",
        VueUiMolecule: "vue-ui-molecule",
        VueUiMoodRadar: "vue-ui-mood-radar",
        VueUiNestedDonuts: "vue-ui-nested-donuts",
        VueUiOnion: "vue-ui-onion",
        VueUiParallelCoordinatePlot: "vue-ui-parallel-coordinate-plot",
        VueUiQuadrant: "vue-ui-quadrant",
        VueUiQuickChart: "vue-ui-quick-chart",
        VueUiRadar: "vue-ui-radar",
        VueUiRating: "vue-ui-rating",
        VueUiRelationCircle: "vue-ui-relation-circle",
        VueUiRings: "vue-ui-rings",
        VueUiScatter: "vue-ui-scatter",
        VueUiScreenshot: "vue-ui-screenshot",
        VueUiSkeleton: "vue-ui-skeleton",
        VueUiSmiley: "vue-ui-smiley",
        VueUiSparkHistogram: "vue-ui-sparkhistogram",
        VueUiSparkStackbar: "vue-ui-sparkstackbar",
        VueUiSparkTrend: "vue-ui-spark-trend",
        VueUiSparkbar: "vue-ui-sparkbar",
        VueUiSparkgauge: "vue-ui-sparkgauge",
        VueUiSparkline: "vue-ui-sparkline",
        VueUiStripPlot: "vue-ui-strip-plot",
        VueUiTable: "vue-ui-table",
        VueUiTableHeatmap: "vue-ui-table-heatmap",
        VueUiTableSparkline: "vue-ui-table-sparkline",
        VueUiThermometer: "vue-ui-thermometer",
        VueUiTimer: "vue-ui-timer",
        VueUiTiremarks: "vue-ui-tiremarks",
        VueUiTreemap: "vue-ui-treemap",
        VueUiHorizontalBar: "vue-ui-horizontal-bar",
        VueUiWaffle: "vue-ui-waffle",
        VueUiWheel: "vue-ui-wheel",
        VueUiWordCloud: "vue-ui-word-cloud",
        VueUiXy: "vue-ui-xy",
        VueUiXyCanvas: "vue-ui-xy-canvas",
        VueUiGizmo: "vue-ui-gizmo",
        VueUiStackbar: "vue-ui-stackbar",
        VueUiFunnel: "vue-ui-funnel",
        VueUiHistoryPlot: "vue-ui-history-plot",
        VueUiCirclePack: "vue-ui-circle-pack",
        VueUiWorld: "vue-ui-world",
        VueUiRidgeline: "vue-ui-ridgeline",
        VueUiChord: "vue-ui-chord",
        VueUiStackline: "vue-ui-stackline",
        VueUiDag: "vue-ui-dag",
        VueUiGeo: "vue-ui-geo",
        VueUiBump: "vue-ui-bump",
        VueUiPattern: "vue-ui-pattern",
        VueUiPatternSeed: "vue-ui-pattern-seed",
    };

    const typesMapping = {
        VueDataUi: null,
        VueUi3dBar: ", type VueUi3dBarDataset, type VueUi3dBarConfig",
        VueUiAccordion: ", type VueUiAccordionConfig",
        VueUiAgePyramid:
            ", type VueUiAgePyramidDataset, type VueUiAgePyramidConfig",
        VueUiAnnotator:
            ", type VueUiAnnotatorDataset, type VueUiAnnotatorConfig",
        VueUiBullet: ", type VueUiBulletDataset, type VueUiBulletConfig",
        VueUiBump: ", type VueUiBumpDatasetItem, type VueUiBumpConfig",
        VueUiCandlestick: ", type OHLC, type VueUiCandlestickConfig",
        VueUiCarouselTable:
            ", type VueUiCarouselTableDataset, type VueUiCarouselTableConfig",
        VueUiChestnut:
            ", type VueUiChestnutDatasetRoot, type VueUiChestnutConfig",
        VueUiChord: ", type VueUiChordDataset, type VueUiChordConfig",
        VueUiCirclePack:
            ", type VueUiCirclePackDatasetItem, type VueUiCirclePackConfig",
        VueUiCursor: ", type VueUiCursorConfig",
        VueUiDag: ", type VueUiDagDataset, type VueUiDagConfig",
        VueUiDashboard:
            ", type VueUiDashboardElement, type VueUiDashboardConfig",
        VueUiDigits: ", type VueUiDigitsConfig",
        VueUiDonut: ", type VueUiDonutDatasetItem, type VueUiDonutConfig",
        VueUiDonutEvolution:
            ", type VueUiDonutEvolutionDatasetItem, type VueUiDonutEvolutionConfig",
        VueUiDumbbell: ", type VueUiDumbbellDataset, type VueUiDumbbellConfig",
        VueUiFlow: ", type VueUiFlowDatasetItem, type VueUiFlowConfig",
        VueUiFunnel: ", type VueUiFunnelDatasetItem, type VueUiFunnelConfig",
        VueUiGalaxy: ", type VueUiGalaxyDatasetItem, type VueUiGalaxyConfig",
        VueUiGauge: ", type VueUiGaugeDataset, type VueUiGaugeConfig",
        VueUiGeo: ", type VueUiGeoDatasetItem, type VueUiGeoConfig",
        VueUiGizmo: ", type VueUiGizmoDataset, type VueUiGizmoConfig",
        VueUiHeatmap: ", type VueUiHeatmapDatasetItem, type VueUiHeatmapConfig",
        VueUiHistoryPlot:
            ", type VueUiHistoryPlotDatasetItem, type VueUiHistoryPlotConfig",
        VueUiHorizontalBar:
            ", type VueUiHorizontalBarDatasetItem, type VueUiHorizontalBarConfig",
        VueUiIcon: "",
        VueUiKpi: ", type VueUiKpiConfig",
        VueUiMiniLoader: ", type VueUiMiniLoaderConfig",
        VueUiMolecule:
            ", type VueUiMoleculeDatasetNode, type VueUiMoleculeConfig",
        VueUiMoodRadar:
            ", type VueUiMoodRadarDataset, type VueUiMoodRadarConfig",
        VueUiNestedDonuts:
            ", type VueUiNestedDonutsDatasetItem, type VueUiNestedDonutsConfig",
        VueUiOnion: ", type VueUiOnionDatasetItem, type VueUiOnionConfig",
        VueUiParallelCoordinatePlot:
            ", type VueUiParallelCoordinatePlotDatasetItem, type VueUiParallelCoordinatePlotConfig",
        VueUiPattern: "",
        VueUiPatternSeed: "",
        VueUiQuadrant:
            ", type VueUiQuadrantDatasetItem, type VueUiQuadrantConfig",
        VueUiQuickChart:
            ", type VueUiQuickChartDataset, type VueUiQuickChartConfig",
        VueUiRadar: ", type VueUiRadarDataset, type VueUiRadarConfig",
        VueUiRating: ", type VueUiRatingDataset, type VueUiRatingConfig",
        VueUiRelationCircle:
            ", type VueUiRelationCircleDatasetItem, type VueUiRelationCircleConfig",
        VueUiRidgeline:
            ", type VueUiRidgelineDatasetItem, type VueUiRidgelineConfig",
        VueUiRings: ", type VueUiRingsDatasetItem, type VueUiRingsConfig",
        VueUiScatter: ", type VueUiScatterDatasetItem, type VueUiScatterConfig",
        VueUiScreenshot: "",
        VueUiSkeleton: ", type VueUiSkeletonConfig",
        VueUiSmiley: ", type VueUiRatingDataset, type VueUiSmileyConfig",
        VueUiSparkHistogram:
            ", type VueUiSparkHistogramDatasetItem, type VueUiSparkHistogramConfig",
        VueUiSparkStackbar:
            ", type VueUiSparkStackbarDatasetItem, type VueUiSparkStackbarConfig",
        VueUiSparkTrend: ", type VueUiSparkTrendConfig",
        VueUiSparkbar:
            ", type VueUiSparkbarDatasetItem, type VueUiSparkbarConfig",
        VueUiSparkgauge:
            ", type VueUiSparkgaugeDataset, type VueUiSparkgaugeConfig",
        VueUiSparkline:
            ", type VueUiSparklineDatasetItem, type VueUiSparklineConfig",
        VueUiStackbar:
            ", type VueUiStackbarDatasetItem, type VueUiStackbarConfig",
        VueUiStackline:
            ", type VueUiStacklineDatasetItem, type VueUiStacklineConfig",
        VueUiStripPlot:
            ", type VueUiStripPlotDataset, type VueUiStripPlotConfig",
        VueUiTable: ", type VueUiTableDataset, type VueUiTableConfig",
        VueUiTableHeatmap:
            ", type VueUiTableHeatmapDatasetItem, type VueUiTableHeatmapConfig",
        VueUiTableSparkline:
            ", type VueUiTableSparklineDatasetItem, type VueUiTableSparklineConfig",
        VueUiThermometer:
            ", type VueUiThermometerDataset, type VueUiThermometerConfig",
        VueUiTimer: ", type VueUiTimerConfig",
        VueUiTiremarks:
            ", type VueUiTiremarksDataset, type VueUiTiremarksConfig",
        VueUiTreemap: ", type VueUiTreemapDatasetItem, type VueUiTreemapConfig",
        VueUiWaffle: ", type VueUiWaffleDatasetItem, type VueUiWaffleConfig",
        VueUiWheel: ", type VueUiWheelDataset, type VueUiWheelConfig",
        VueUiWordCloud:
            ", type VueUiWordCloudDatasetItem, type VueUiWordCloudConfig",
        VueUiWorld: ", type VueUiWorldDataset, type VueUiWorldConfig",
        VueUiXy: ", type VueUiXyDatasetItem, type VueUiXyConfig",
        VueUiXyCanvas:
            ", type VueUiXyCanvasDatasetItem, type VueUiXyCanvasConfig",
    };

    const datasetTypeMap = {
        VueDataUi: "",
        VueUi3dBar: "VueUi3dBarDataset",
        VueUiAccordion: "",
        VueUiAgePyramid: "VueUiAgePyramidDataset",
        VueUiAnnotator: "VueUiAnnotatorDataset",
        VueUiBullet: "VueUiBulletDataset",
        VueUiBump: "VueUiBumpDatasetItem[]",
        VueUiCandlestick: "OHLC[]",
        VueUiCarouselTable: "VueUiCarouselTableDataset",
        VueUiChestnut: "VueUiChestnutDatasetRoot[]",
        VueUiChord: "VueUiChordDataset",
        VueUiCirclePack: "VueUiCirclePackDatasetItem[]",
        VueUiCursor: "",
        VueUiDag: "VueUiDagDataset",
        VueUiDashboard: "VueUiDashboardElement[]",
        VueUiDigits: "",
        VueUiDonut: "VueUiDonutDatasetItem[]",
        VueUiDonutEvolution: "VueUiDonutEvolutionDatasetItem[]",
        VueUiDumbbell: "VueUiDumbbellDataset[]",
        VueUiFlow: "VueUiFlowDatasetItem[]",
        VueUiFunnel: "VueUiFunnelDatasetItem[]",
        VueUiGalaxy: "VueUiGalaxyDatasetItem[]",
        VueUiGauge: "VueUiGaugeDataset",
        VueUiGeo: "VueUiGeoDatasetItem[]",
        VueUiGizmo: "VueUiGizmoDataset",
        VueUiHeatmap: "VueUiHeatmapDatasetItem[]",
        VueUiHistoryPlot: "VueUiHistoryPlotDatasetItem[]",
        VueUiHorizontalBar: "VueUiHorizontalBarDatasetItem[]",
        VueUiIcon: "",
        VueUiKpi: "",
        VueUiMiniLoader: "",
        VueUiMolecule: "VueUiMoleculeDatasetNode[]",
        VueUiMoodRadar: "VueUiMoodRadarDataset",
        VueUiNestedDonuts: "VueUiNestedDonutsDatasetItem[]",
        VueUiOnion: "VueUiOnionDatasetItem[]",
        VueUiParallelCoordinatePlot: "VueUiParallelCoordinatePlotDatasetItem[]",
        VueUiPattern: "",
        VueUiPatternSeed: "",
        VueUiQuadrant: "VueUiQuadrantDatasetItem[]",
        VueUiQuickChart: "VueUiQuickChartDataset",
        VueUiRadar: "VueUiRadarDataset",
        VueUiRating: "VueUiRatingDataset",
        VueUiRelationCircle: "VueUiRelationCircleDatasetItem[]",
        VueUiRidgeline: "VueUiRidgelineDatasetItem[]",
        VueUiRings: "VueUiRingsDatasetItem[]",
        VueUiScatter: "VueUiScatterDatasetItem[]",
        VueUiScreenshot: "",
        VueUiSkeleton: "",
        VueUiSmiley: "VueUiRatingDataset",
        VueUiSparkHistogram: "VueUiSparkHistogramDatasetItem[]",
        VueUiSparkStackbar: "VueUiSparkStackbarDatasetItem[]",
        VueUiSparkTrend: "",
        VueUiSparkbar: "VueUiSparkbarDatasetItem[]",
        VueUiSparkgauge: "VueUiSparkgaugeDataset",
        VueUiSparkline: "VueUiSparklineDatasetItem[]",
        VueUiStackbar: "VueUiStackbarDatasetItem[]",
        VueUiStackline: "VueUiStacklineDatasetItem[]",
        VueUiStripPlot: "VueUiStripPlotDataset[]",
        VueUiTable: "VueUiTableDataset",
        VueUiTableHeatmap: "VueUiTableHeatmapDatasetItem[]",
        VueUiTableSparkline: "VueUiTableSparklineDatasetItem[]",
        VueUiThermometer: "VueUiThermometerDataset",
        VueUiTimer: "",
        VueUiTiremarks: "VueUiTiremarksDataset",
        VueUiTreemap: "VueUiTreemapDatasetItem[]",
        VueUiWaffle: "VueUiWaffleDatasetItem[]",
        VueUiWheel: "VueUiWheelDataset",
        VueUiWordCloud: "VueUiWordCloudDatasetItem[]",
        VueUiWorld: "VueUiWorldDataset",
        VueUiXy: "VueUiXyDatasetItem[]",
        VueUiXyCanvas: "VueUiXyCanvasDatasetItem[]",
    };

    const configTypeMap = {
        VueDataUi: "",
        VueUi3dBar: "VueUi3dBarConfig",
        VueUiAccordion: "VueUiAccordionConfig",
        VueUiAgePyramid: "VueUiAgePyramidConfig",
        VueUiAnnotator: "VueUiAnnotatorConfig",
        VueUiBullet: "VueUiBulletConfig",
        VueUiBump: "VueUiBumpConfig",
        VueUiCandlestick: "VueUiCandlestickConfig",
        VueUiCarouselTable: "VueUiCarouselTableConfig",
        VueUiChestnut: "VueUiChestnutConfig",
        VueUiChord: "VueUiChordConfig",
        VueUiCirclePack: "VueUiCirclePackConfig",
        VueUiCursor: "VueUiCursorConfig",
        VueUiDag: "VueUiDagConfig",
        VueUiDashboard: "VueUiDashboardConfig",
        VueUiDigits: "VueUiDigitsConfig",
        VueUiDonut: "VueUiDonutConfig",
        VueUiDonutEvolution: "VueUiDonutEvolutionConfig",
        VueUiDumbbell: "VueUiDumbbellConfig",
        VueUiFlow: "VueUiFlowConfig",
        VueUiFunnel: "VueUiFunnelConfig",
        VueUiGalaxy: "VueUiGalaxyConfig",
        VueUiGauge: "VueUiGaugeConfig",
        VueUiGeo: "VueUiGeoConfig",
        VueUiGizmo: "VueUiGizmoConfig",
        VueUiHeatmap: "VueUiHeatmapConfig",
        VueUiHistoryPlot: "VueUiHistoryPlotConfig",
        VueUiHorizontalBar: "VueUiHorizontalBarConfig",
        VueUiIcon: "",
        VueUiKpi: "VueUiKpiConfig",
        VueUiMiniLoader: "VueUiMiniLoaderConfig",
        VueUiMolecule: "VueUiMoleculeConfig",
        VueUiMoodRadar: "VueUiMoodRadarConfig",
        VueUiNestedDonuts: "VueUiNestedDonutsConfig",
        VueUiOnion: "VueUiOnionConfig",
        VueUiParallelCoordinatePlot: "VueUiParallelCoordinatePlotConfig",
        VueUiPattern: "",
        VueUiPatternSeed: "",
        VueUiQuadrant: "VueUiQuadrantConfig",
        VueUiQuickChart: "VueUiQuickChartConfig",
        VueUiRadar: "VueUiRadarConfig",
        VueUiRating: "VueUiRatingConfig",
        VueUiRelationCircle: "VueUiRelationCircleConfig",
        VueUiRidgeline: "VueUiRidgelineConfig",
        VueUiRings: "VueUiRingsConfig",
        VueUiScatter: "VueUiScatterConfig",
        VueUiScreenshot: "",
        VueUiSkeleton: "VueUiSkeletonConfig",
        VueUiSmiley: "VueUiSmileyConfig",
        VueUiSparkHistogram: "VueUiSparkHistogramConfig",
        VueUiSparkStackbar: "VueUiSparkStackbarConfig",
        VueUiSparkTrend: "VueUiSparkTrendConfig",
        VueUiSparkbar: "VueUiSparkbarConfig",
        VueUiSparkgauge: "VueUiSparkgaugeConfig",
        VueUiSparkline: "VueUiSparklineConfig",
        VueUiStackbar: "VueUiStackbarConfig",
        VueUiStackline: "VueUiStacklineConfig",
        VueUiStripPlot: "VueUiStripPlotConfig",
        VueUiTable: "VueUiTableConfig",
        VueUiTableHeatmap: "VueUiTableHeatmapConfig",
        VueUiTableSparkline: "VueUiTableSparklineConfig",
        VueUiThermometer: "VueUiThermometerConfig",
        VueUiTimer: "VueUiTimerConfig",
        VueUiTiremarks: "VueUiTiremarksConfig",
        VueUiTreemap: "VueUiTreemapConfig",
        VueUiWaffle: "VueUiWaffleConfig",
        VueUiWheel: "VueUiWheelConfig",
        VueUiWordCloud: "VueUiWordCloudConfig",
        VueUiWorld: "VueUiWorldConfig",
        VueUiXy: "VueUiXyConfig",
        VueUiXyCanvas: "VueUiXyCanvasConfig",
    };

    return mapping[c]
        ? {
              universal: `import { VueDataUi } from "vue-data-ui";`,
              universalTyped: `import { VueDataUi${typesMapping[c]} } from "vue-data-ui";`,
              untyped: `import { ${c} } from "vue-data-ui/${mapping[c]}";`,
              untypedNotTreeshaken: `import { ${c} } from "vue-data-ui";`,
              classic: `import { ${c}${typesMapping[c]} } from "vue-data-ui";`,
              treeshaken: `import { ${c}${typesMapping[c]} } from "vue-data-ui/${mapping[c]}";`,
              datasetType: datasetTypeMap[c],
              configType: configTypeMap[c],
          }
        : null;
}
