export function useIconMap(componentName) {
    const mapping = {
        VueUiBullet: 'chartBullet',
        VueUi3dBar: 'chart3dBar',
        VueUiAccordion: 'accordion',
        VueUiAgePyramid: 'chartAgePyramid',
        VueUiAnnotator: 'annotator',
        VueUiCandlestick: 'chartCandlestick',
        VueUiCarouselTable: 'carouselTable',
        VueUiChestnut: 'chartChestnut',
        VueUiCursor: 'cursor',
        VueUiDashboard: 'dashboard',
        VueUiDigits: 'digit8',
        VueUiDonut: 'chartDonut',
        VueUiDonutEvolution: 'chartDonutEvolution',
        VueUiDumbbell: 'chartDumbbell',
        VueUiFlow: 'chartFlow',
        VueUiGalaxy: 'chartGalaxy',
        VueUiGauge: 'chartGauge',
        VueUiHeatmap: 'chartHeatmap',
        VueUiIcon: 'smiley',
        VueUiKpi: 'kpiBox',
        VueUiMiniLoader: 'chartWheel',
        VueUiMolecule: 'chartCluster',
        VueUiMoodRadar: 'chartMoodRadar',
        VueUiNestedDonuts: 'chartNestedDonuts',
        VueUiOnion: 'chartOnion',
        VueUiParallelCoordinatePlot: 'chartParallelCoordinatePlot',
        VueUiQuadrant: 'chartQuadrant',
        VueUiQuickChart: 'vueDataUi',
        VueUiRadar: 'chartRadar',
        VueUiRating: 'star',
        VueUiRelationCircle: 'chartRelationCircle',
        VueUiRings: 'chartRings',
        VueUiScatter: 'chartScatter',
        VueUiScreenshot: 'screenshot',
        VueUiSkeleton: 'skeleton',
        VueUiSmiley: 'smiley',
        VueUiSparkHistogram: 'chartSparkHistogram',
        VueUiSparkStackbar: 'chartSparkStackbar',
        VueUiSparkTrend: 'trend',
        VueUiSparkbar: 'chartSparkbar',
        VueUiSparkgauge: 'chartGauge',
        VueUiSparkline: 'chartSparkline',
        VueUiStripPlot: 'chartStripPlot',
        VueUiTable: 'chartTable',
        VueUiTableHeatmap: 'chartTable',
        VueUiTableSparkline: 'chartTableSparkline',
        VueUiThermometer: 'chartThermometer',
        VueUiTimer: 'lap',
        VueUiTiremarks: 'chartTiremarks',
        VueUiTreemap: 'chartTreemap',
        VueUiVerticalBar: 'chartVerticalBar',
        VueUiWaffle: 'chartWaffle',
        VueUiWheel: 'chartWheel',
        VueUiWordCloud: 'chartWordCloud',
        VueUiXy: 'chartLine',
        VueUiXyCanvas: 'chartLine',
        VueUiGizmo: 'battery',
        VueUiStackbar: 'chartStackbar',
        VueUiFunnel: 'chartFunnel',
        VueUiHistoryPlot: 'chartHistoryPlot'
    }
    return mapping[componentName] || 'clipBoard';
}

export function isValidComponent(content) {
    const valid = [
        'VueUi3dBar',
        'VueUiAccordion',
        'VueUiAgePyramid',
        'VueUiAnnotator',
        'VueUiBullet',
        'VueUiCandlestick',
        'VueUiCarouselTable',
        'VueUiChestnut',
        'VueUiCursor',
        'VueUiDashboard',
        'VueUiDigits',
        'VueUiDonut',
        'VueUiDonutEvolution',
        'VueUiDumbbell',
        'VueUiFlow',
        'VueUiFunnel',
        'VueUiGalaxy',
        'VueUiGauge',
        'VueUiGizmo',
        'VueUiHeatmap',
        'VueUiIcon',
        'VueUiKpi',
        'VueUiMiniLoader',
        'VueUiMolecule',
        'VueUiMoodRadar',
        'VueUiNestedDonuts',
        'VueUiOnion',
        'VueUiParallelCoordinatePlot',
        'VueUiQuadrant',
        'VueUiQuickChart',
        'VueUiRadar',
        'VueUiRating',
        'VueUiRelationCircle',
        'VueUiRings',
        'VueUiScatter',
        'VueUiScreenshot',
        'VueUiSkeleton',
        'VueUiSmiley',
        'VueUiSparkHistogram',
        'VueUiSparkStackbar',
        'VueUiSparkTrend',
        'VueUiSparkbar',
        'VueUiSparkgauge',
        'VueUiSparkline',
        'VueUiStackbar',
        'VueUiStripPlot',
        'VueUiTable',
        'VueUiTableHeatmap',
        'VueUiTableSparkline',
        'VueUiThermometer',
        'VueUiTimer',
        'VueUiTiremarks',
        'VueUiTreemap',
        'VueUiVerticalBar',
        'VueUiWaffle',
        'VueUiWheel',
        'VueUiWordCloud',
        'VueUiXy',
        'VueUiXyCanvas',
        'VueUiHistoryPlot',
    ];

    return valid.includes(content);
}