export function useIconMap(componentName) {
    const mapping = {
        VueUiSparkline: 'chartSparkline',
        VueUiSparkbar: 'chartSparkbar',
        VueUiSparkStackbar: 'chartSparkStackbar',
        VueUiSparkHistogram: 'chartSparkHistogram',
        VueUiSparkgauge: 'chartGauge',
        VueUiSparkTrend: 'trend',
        VueUiQuickChart: 'vueDataUi',
        VueUiXy: 'chartLine',
        VueUiXyCanvas: 'chartLine',
        VueUiVerticalBar: 'chartVerticalBar',
        VueUiParallelCoordinatePlot: 'chartParallelCoordinatePlot',
        VueUiFlow: 'chartFlow',
        VueUiCandlestick: 'chartCandlestick',
        VueUiAgePyramid: 'chartAgePyramid',
        VueUiDonutEvolution: 'chartDonutEvolution',
        VueUiDonut: 'chartDonut',
        VueUiNestedDonuts: 'chartNestedDonuts',
        VueUiWaffle: 'chartWaffle',
        VueUiHeatmap: 'chartHeatmap',
        VueUiTreemap: 'chartTreemap',
        VueUiRings: 'chartRings',
        VueUiGalaxy: 'chartGalaxy',
        VueUiChestnut: 'chartChestnut',
        VueUiGauge: 'chartGauge',
        VueUiOnion: 'chartOnion',
        VueUiWheel: 'chartWheel',
        VueUiTiremarks: 'chartTiremarks',
        VueUiThermometer: 'chartThermometer',
        VueUiWordCloud: 'chartWordCloud',
        VueUiRelationCircle: 'chartRelationCircle',
        VueUiRadar: 'chartRadar',
        VueUiMoodRadar: 'chartMoodRadar',
        VueUiQuadrant: 'chartQuadrant',
        VueUiScatter: 'chartScatter',
        VueUiMolecule: 'chartCluster',
        VueUiStripPlot: 'chartStripPlot',
        VueUiDumbbell: 'chartDumbbell',
        VueUi3dBar: 'chart3dBar',
        VueUiTableSparkline: 'chartTable',
        VueUiTableHeatmap: 'chartTable',
        VueUiTable: 'chartTable',
        VueUiCarouselTable: 'carouselTable',
        VueUiRating: 'star',
        VueUiSmiley: 'smiley',
        VueUiAccordion: 'accordion',
        VueUiScreenshot: 'screenshot',
        VueUiSkeleton: 'skeleton',
        VueUiDashboard: 'dashboard',
        VueUiAnnotator: 'annotator',
        VueUiIcon: 'smiley',
        VueUiDigits: 'digit8',
        VueUiCursor: 'cursor',
        VueUiMiniLoader: 'chartWheel',
        VueUiKpi: 'kpiBox',
        VueUiTimer: 'lap'
    }

    return mapping[componentName] || 'clipBoard';
}